### ISSUE TITLE
Whats the error?

### ISSUE THREAD

**Issue by LPDMinecraft** [Mokulu/discord-oauth2-api#6]
> Exception in thread "main" java.lang.ClassCastException: class org.simpleyaml.configuration.MemorySection cannot be cast to class java.lang.String (org.simpleyaml.configuration.MemorySection is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
> 	at de.lcraft.mee7.bot.Bot.makeOthConnection(Bot.java:29)
> 	at de.lcraft.mee7.menu.Start.main(Start.java:15)

Thats my error and all things you can see [my project](https://github.com/Lcraft-Developers/MEE7/blob/main/java-workspace/MEE7%20JDA%20Discord%20Bot/src/main/java/de/lcraft/mee7/bot/Bot.java)

**Comment by Mokulu** [comment]
This error is related to your YAML parser, not this API. From the stack trace, you’re trying to cast a config section to a string.
